[package]
name = "rbca_core"
version = "0.1.0"
edition = "2021"
authors = ["Max Gilmour"]
repository = "https://github.com/maxgmr/rbca"

[dependencies]
strum = "0.26"
strum_macros = "0.26"

[dev-dependencies]
pretty_assertions = "1.4"
text_io = "0.1"
