[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
authors = ["Max Gilmour"]
repository = "https://github.com/maxgmr/rbca"

[dependencies]
color-eyre = "0.6"
rbca_core = { path = "../rbca_core" }
sdl2 = "0.37"
text_io = "0.1"
